//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CustomerInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomarId { get; set; }
        [DisplayName("Code")]
        public string CustomerCode { get; set; }

        [DisplayName("Name")]
        public string CustomerName { get; set; }
        [DisplayName("Address")]
        public string CustomerAddesss { get; set; }

        [DisplayName("PostCode")]
        public string PostCode { get; set; }
        [DisplayName("TelePhone")]
        public string Telephone { get; set; }

        [DisplayName("Email Address")]

        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }

        [DisplayName("Contact Person Name")]
        public string ContactPersonName { get; set; }

        [DisplayName("Postion")]
        public Nullable<int> ContactPersonPosition { get; set; }
        [DisplayName("Region")]
        public Nullable<int> ContactRegion { get; set; }


        [DisplayName("Category")]
        public Nullable<int> CustomerCategory { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Region Region { get; set; }
    }
}
